// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Zfh1tEd_8-EMtLLVqRN-7vJCPg46OwQ',
    appId: '1:640025559275:web:9368a31d7689e1e915beae',
    messagingSenderId: '640025559275',
    projectId: 'attendease-dev',
    authDomain: 'attendease-dev.firebaseapp.com',
    storageBucket: 'attendease-dev.firebasestorage.app',
    measurementId: 'G-NZR8NP49H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFzuidB6goIRNymD_0-yO4zkvzRooCmA',
    appId: '1:640025559275:android:c5a8e0b7f6bf6c3815beae',
    messagingSenderId: '640025559275',
    projectId: 'attendease-dev',
    storageBucket: 'attendease-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXVPODU_V4FCmxIIgFd1lDTygeXusu61E',
    appId: '1:640025559275:ios:f7484efd78ee4fb915beae',
    messagingSenderId: '640025559275',
    projectId: 'attendease-dev',
    storageBucket: 'attendease-dev.firebasestorage.app',
    iosBundleId: 'com.attendease.app',
  );
}
